/*
 * Mega Happy Sprite is released under the BSD 3-Clause license.
 * read LICENSE for more info
 */


static const char *arrow_data[] = {
 " 32 32 3 1",
 "X c #000000",
 ". c #ffffff",
 "  c None",
 "X                               ",
 "XX                              ",
 "X.X                             ",
 "X..X                            ",
 "X...X                           ",
 "X....X                          ",
 "X.....X                         ",
 "X......X                        ",
 "X.......X                       ",
 "X........X                      ",
 "X.....XXXXX                     ",
 "X..X..X                         ",
 "X.X X..X                        ",
 "XX  X..X                        ",
 "X    X..X                       ",
 "     X..X                       ",
 "      X..X                      ",
 "      X..X                      ",
 "       XX                       ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "0,0"
};

static const char *horizontal_data[] = {
 " 32 32 3 1",
 "X c #000000",
 ". c #ffffff",
 "  c None",
 "                                ",
 "                                ",
 "        XX   XX                 ",
 "       X.X   X.X                ",
 "      X..X   X..X               ",
 "     X...X   X...X              ",
 "    X....X   X....X             ",
 "   X.....X   X.....X            ",
 "  X......X   X......X           ",
 " X.......X   X.......X          ",
 "X........X   X........X         ",
 " X.......X   X.......X          ",
 "  X......X   X......X           ",
 "   X.....X   X.....X            ",
 "    X....X   X....X             ",
 "     X...X   X...X              ",
 "      X..X   X..X               ",
 "       X.X   X.X                ",
 "        XX   XX                 ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "10,11"
};

static const char *vertical_data[] = {
 " 32 32 3 1",
 "X c #000000",
 ". c #ffffff",
 "  c None",
 "           X                    ",
 "          X.X                   ",
 "         X...X                  ",
 "        X.....X                 ",
 "       X.......X                ",
 "      X.........X               ",
 "     X...........X              ",
 "    X.............X             ",
 "   X...............X            ",
 "   XXXXXXXXXXXXXXXXX            ",
 "                                ",
 "                                ",
 "                                ",
 "   XXXXXXXXXXXXXXXXX            ",
 "   X...............X            ",
 "    X.............X             ",
 "     X...........X              ",
 "      X.........X               ",
 "       X.......X                ",
 "        X.....X                 ",
 "         X...X                  ",
 "          X.X                   ",
 "           X                    ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "11,11"
};

static const char *cross_scroll_a_data[] = {
 " 32 32 3 1",
 "X c #000000",
 ". c #ffffff",
 "  c None",
 "            X                   ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 " XXXXXXXX       XXXXXXXX        ",
 "X........       ........X       ",
 " XXXXXXXX       XXXXXXXX        ",
 "           X.X                  ",
 "           X.X      X           ",
 "           X.X     X.X          ",
 "           X.X    X.X.X         ",
 "           X.X   X.X X.X        ",
 "            X   X.XXXXX.X       ",
 "                X.......X       ",
 "                X.XXXXX.X       ",
 "                X.X   X.X       ",
 "                XXX   XXX       ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "12,7"
};

static const char *cross_scroll_b_data[] = {
 " 32 32 3 1",
 "X c #000000",
 ". c #ffffff",
 "  c None",
 "            X                   ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 " XXXXXXXX       XXXXXXXX        ",
 "X........       ........X       ",
 " XXXXXXXX       XXXXXXXX        ",
 "           X.X                  ",
 "           X.X XXXXX            ",
 "           X.X X....X           ",
 "           X.X X.XXX.X          ",
 "           X.X X.XXXX.X         ",
 "            X  X.....X          ",
 "               X.XXXX.X         ",
 "               X.XXX.X          ",
 "               X....X           ",
 "               XXXXX            ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "12,7"
};


static const char *cross_sprite_data[] = {
 " 32 32 3 1",
 "X c #000000",
 ". c #ffffff",
 "  c None",
 "            X                   ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 " XXXXXXXX       XXXXXXXX        ",
 "X........       ........X       ",
 " XXXXXXXX       XXXXXXXX        ",
 "           X.X                  ",
 "           X.X    XXXXXX        ",
 "           X.X   X.....X        ",
 "           X.X  X.XXXXXX        ",
 "           X.X X.XXXX           ",
 "            X   X....X          ",
 "                 XXXX.X         ",
 "               XXXXXXX.X        ",
 "               X......X         ",
 "               XXXXXXX          ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "12,7"
};




static const char *cross_data[] = {
 " 32 32 3 1",
 "X c #000000",
 ". c #ffffff",
 "  c None",
 "            X                   ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 " XXXXXXXX       XXXXXXXX        ",
 "X........       ........X       ",
 " XXXXXXXX       XXXXXXXX        ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 "           X.X                  ",
 "            X                   ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "12,7"
};



static const char *no_data[] = {
 " 32 32 3 1",
 "X c #000000",
 ". c #ffffff",
 "  c None",
 "  X           X                 ",
 " X.X         X.X                ",
 "X...X       X...X               ",
 " X...X     X...X                ",
 "  X...X   X...X                 ",
 "   X...X X...X                  ",
 "    X...X...X                   ",
 "     X.....X                    ",
 "      X...X                     ",
 "     X.....X                    ",
 "    X...X...X                   ",
 "   X...X X...X                  ",
 "  X...X   X...X                 ",
 " X...X     X...X                ",
 "X...X       X...X               ",
 " X.X         X.X                ",
 "  X           X                 ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "8,8"
};

static const char *ver_a_flip_data[] = {
 " 32 32 3 1",
 "X c #000000",
 ". c #ffffff",
 "  c None",
 "    XX                          ",
 "   X..X                         ",
 "  X....X                        ",
 " X......X                       ",
 "X........X                      ",
 "X........X                      ",
 "XXXXXX..XX                      ",
 "     X..X                       ",
 "     X..X                       ",
 "  X  X..X                       ",
 " X.X X..X        X              ",
 " X..XX..X       X.X             ",
 " X..XX..X      X.X.X            ",
 " X..XX..X     X.X X.X           ",
 " X..XX..X    X.XXXXX.X          ",
 " X..XX..X    X.......X          ",
 " X..XX..X    X.XXXXX.X          ",
 " X..XX..X    X.X   X.X          ",
 " X..XX..X    XXX   XXX          ",
 " X..XX..X                       ",
 " X..XX..X                       ",
 " X..X X.X                       ",
 " X..X  X                        ",
 " X..X                           ",
 " X..X                           ",
 "XX..XXXXXX                      ",
 "X........X                      ",
 "X........X                      ",
 " X......X                       ",
 "  X....X                        ",
 "   X..X                         ",
 "    XX                          ",
 "4,0"
};


static const char *hor_a_flip_data[] = {
 " 32 32 3 1",
 "X c #000000",
 ". c #ffffff",
 "  c None",
 "    XXX                  XXX    ",
 "   X..X   XXXXXXXXXXXXXXXX..X   ",
 "  X...X  X...................X  ",
 " X....X   X...................X ",
 "X.....X    XXXXXXXXXXXXXXX.....X",
 "X.....XXXXXXXXXXXXXXX    X.....X",
 " X...................X   X....X ",
 "  X...................X  X...X  ",
 "   X..XXXXXXXXXXXXXXXX   X..X   ",
 "    XXX                  XXX    ",
 "                                ",
 "               X                ",
 "              X.X               ",
 "             X.X.X              ",
 "            X.X X.X             ",
 "           X.XXXXX.X            ",
 "           X.......X            ",
 "           X.XXXXX.X            ",
 "           X.X   X.X            ",
 "           XXX   XXX            ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "0,4"
};

static const char *ver_b_flip_data[] = {
 " 32 32 3 1",
 "X c #000000",
 ". c #ffffff",
 "  c None",
 "    XX                          ",
 "   X..X                         ",
 "  X....X                        ",
 " X......X                       ",
 "X........X                      ",
 "X........X                      ",
 "XXXXXX..XX                      ",
 "     X..X                       ",
 "     X..X                       ",
 "  X  X..X                       ",
 " X.X X..X                       ",
 " X..XX..X     XXXXX             ",
 " X..XX..X     X....X            ",
 " X..XX..X     X.XXX.X           ",
 " X..XX..X     X.XXXX.X          ",
 " X..XX..X     X.....X           ",
 " X..XX..X     X.XXXX.X          ",
 " X..XX..X     X.XXX.X           ",
 " X..XX..X     X....X            ",
 " X..XX..X     XXXXX             ",
 " X..XX..X                       ",
 " X..X X.X                       ",
 " X..X  X                        ",
 " X..X                           ",
 " X..X                           ",
 "XX..XXXXXX                      ",
 "X........X                      ",
 "X........X                      ",
 " X......X                       ",
 "  X....X                        ",
 "   X..X                         ",
 "    XX                          ",
 "4,0"
};


static const char *hor_b_flip_data[] = {
 " 32 32 3 1",
 "X c #000000",
 ". c #ffffff",
 "  c None",
 "    XXX                  XXX    ",
 "   X..X   XXXXXXXXXXXXXXXX..X   ",
 "  X...X  X...................X  ",
 " X....X   X...................X ",
 "X.....X    XXXXXXXXXXXXXXX.....X",
 "X.....XXXXXXXXXXXXXXX    X.....X",
 " X...................X   X....X ",
 "  X...................X  X...X  ",
 "   X..XXXXXXXXXXXXXXXX   X..X   ",
 "    XXX                  XXX    ",
 "                                ",
 "           XXXXX                ",
 "           X....X               ",
 "           X.XXX.X              ",
 "           X.XXXX.X             ",
 "           X.....X              ",
 "           X.XXXX.X             ",
 "           X.XXX.X              ",
 "           X....X               ",
 "           XXXXX                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "                                ",
 "0,4"
};
